DELETE FROM Produkty;

SET IDENTITY_INSERT Produkty ON;
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (1, 'Oversized Blazer', NULL, 599.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (2, 'Minimalist Shirt', NULL, 299.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (3, 'Wool Blend Coat', NULL, 899.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (4, 'Structured Bag', NULL, 459.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (5, 'Silk Blouse', NULL, 399.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (6, 'High Waist Jeans', NULL, 349.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (7, 'Cashmere Sweater', NULL, 699.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (8, 'Pleated Midi Skirt', NULL, 499.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (9, 'Leather Jacket', NULL, 1299.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (10, 'Linen Dress', NULL, 549.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (11, 'Wool Beret', NULL, 199.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (12, 'Satin Slip Dress', NULL, 599.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (101, 'Minimalist Overcoat', NULL, 899.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (102, 'Structured Shirt', NULL, 349.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (103, 'Wool Sweater', NULL, 499.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (104, 'Leather Boots', NULL, 799.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (105, 'Slim Fit Jeans', NULL, 399.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (106, 'Bomber Jacket', NULL, 649.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (107, 'Merino Turtleneck', NULL, 449.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (108, 'Tailored Trousers', NULL, 499.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (109, 'Leather Wallet', NULL, 249.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (110, 'Cashmere Scarf', NULL, 349.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (111, 'Leather Belt', NULL, 199.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (112, 'Wool Coat', NULL, 999.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (201, 'Bluza z kapturem', NULL, 129.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (202, 'Spodnie dresowe', NULL, 89.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (203, 'Kurtka zimowa', NULL, 249.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (204, 'T-shirt z nadrukiem', NULL, 49.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (205, 'Sukienka w kropki', NULL, 119.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (206, 'Jeansy z naszywkami', NULL, 129.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (207, 'Sweter z wełny', NULL, 149.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (208, 'Czapka zimowa', NULL, 59.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (209, 'Kalosze', NULL, 89.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (210, 'Piżama bawełniana', NULL, 79.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (211, 'Szalik i rękawiczki', NULL, 69.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (212, 'Kombinezon zimowy', NULL, 299.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (301, 'Skórzana torebka', NULL, 499.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (302, 'Złoty naszyjnik', NULL, 349.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (303, 'Skórzany pasek', NULL, 199.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (304, 'Jedwabny szalik', NULL, 259.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (305, 'Srebrne kolczyki', NULL, 199.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (306, 'Wełniany beret', NULL, 129.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (307, 'Skórzane rękawiczki', NULL, 179.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (308, 'Zegarek minimalistyczny', NULL, 599.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (309, 'Skórzany portfel', NULL, 249.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (310, 'Okulary przeciwsłoneczne', NULL, 299.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (311, 'Jedwabna apaszka', NULL, 179.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (312, 'Skórzana aktówka', NULL, 799.00, 'Accessories', 100);
SET IDENTITY_INSERT Produkty OFF;
