DELETE FROM Produkty;

SET IDENTITY_INSERT Produkty ON;
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (1, 'Marynarka oversize', NULL, 599.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (2, 'Koszula minimalistyczna', NULL, 299.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (3, 'Płaszcz z domieszką wełny', NULL, 899.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (4, 'Torebka o usztywnianym fasonie', NULL, 459.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (5, 'Jedwabna bluzka', NULL, 399.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (6, 'Jeansy z wysokim stanem', NULL, 349.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (7, 'Sweter kaszmirowy', NULL, 699.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (8, 'Plisowana spódnica midi', NULL, 499.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (9, 'Kurtka skórzana', NULL, 1299.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (10, 'Lniana sukienka', NULL, 549.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (11, 'Beret z wełny', NULL, 199.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (12, 'Satynowa sukienka na ramiączkach', NULL, 599.00, 'Women', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (101, 'Płaszcz minimalistyczny', NULL, 899.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (102, 'Koszula o prostym kroju', NULL, 349.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (103, 'Wełniany sweter', NULL, 499.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (104, 'Skórzane buty', NULL, 799.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (105, 'Jeansy slim fit', NULL, 399.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (106, 'Kurtka bomberka', NULL, 649.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (107, 'Golf z merynosów', NULL, 449.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (108, 'Spodnie garniturowe', NULL, 499.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (109, 'Skórzany portfel męski', NULL, 249.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (110, 'Szalik kaszmirowy', NULL, 349.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (111, 'Skórzany pasek', NULL, 199.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (112, 'Płaszcz wełniany', NULL, 999.00, 'Men', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (201, 'Bluza z kapturem', NULL, 129.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (202, 'Spodnie dresowe', NULL, 89.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (203, 'Kurtka zimowa', NULL, 249.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (204, 'T-shirt z nadrukiem', NULL, 49.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (205, 'Sukienka w kropki', NULL, 119.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (206, 'Jeansy z naszywkami', NULL, 129.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (207, 'Sweter z wełny', NULL, 149.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (208, 'Czapka zimowa', NULL, 59.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (209, 'Kalosze', NULL, 89.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (210, 'Piżama bawełniana', NULL, 79.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (211, 'Szalik i rękawiczki', NULL, 69.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (212, 'Kombinezon zimowy', NULL, 299.00, 'Kids', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (301, 'Skórzana torebka', NULL, 499.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (302, 'Złoty naszyjnik', NULL, 349.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (303, 'Skórzany pasek', NULL, 199.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (304, 'Jedwabny szalik', NULL, 259.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (305, 'Srebrne kolczyki', NULL, 199.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (306, 'Wełniany beret', NULL, 129.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (307, 'Skórzane rękawiczki', NULL, 179.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (308, 'Zegarek minimalistyczny', NULL, 599.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (309, 'Skórzany portfel', NULL, 249.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (310, 'Okulary przeciwsłoneczne', NULL, 299.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (311, 'Jedwabna apaszka', NULL, 179.00, 'Accessories', 100);
INSERT INTO Produkty (Id, Nazwa, Opis, Cena, Kategoria, StanMagazynowy) VALUES (312, 'Skórzana aktówka', NULL, 799.00, 'Accessories', 100);
SET IDENTITY_INSERT Produkty OFF;
